'''Run from command line to test the word suggestions generated by given input.
'''
import sys
import operator
import trie
import worddata
import debug


def main():
    atrie = trie.Trie()
    atrie.build_from_trie('../data/Word Frequency Dictionary - Full - trieform.txt')

    print 'Initialized.'

    while True:
        input = raw_input()
        if input == '': continue
        result_list = atrie.get_potential_words(input, 1)
        if result_list.result_dict: # if is not empty
            print '\nRESULTS:'
            for result in result_list.sort_results():
                print str(result.error_count) + ' ' + result.data
        else:
            print'\nRESULTS:'
            print'[empty]'
        print ''

main()
